# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_squashed_0003_auto_20160506_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_comments',
            field=models.ManyToManyField(blank=True, null=True, to='main.Comment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_submissions',
            field=models.ManyToManyField(blank=True, null=True, to='main.Submission'),
        ),
    ]
