# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20160506_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcodeinstance',
            name='coder',
        ),
        migrations.RemoveField(
            model_name='submissioncodeinstance',
            name='coder',
        ),
    ]
