# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 04:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'main', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created_ut', models.IntegerField(blank=True, null=True)),
                ('created_utc', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=24, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=8, null=True)),
                ('article', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created_ut', models.IntegerField(blank=True, null=True)),
                ('created_utc', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=24, null=True)),
                ('in_set', models.NullBooleanField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'managed': False,
            },
        ),
    ]
